[project]
name = "ai-object-detection-using-yolov8-haar-cascade"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.2",
    "opencv-python>=4.12.0.88",
    "streamlit>=1.52.2",
    "ultralytics>=8.3.243",
]
